### ISSUE TITLE
Not reactive...

### ISSUE THREAD

**Issue by cpgb85** [dreambo8563/next-vue-storage-watcher#3]
I thought this library was reactive.  Unless i'm missing something, I thought that meant when I change a localStorage value, it changes the value that i used in my template.

**Comment by dreambo8563** [comment]
pls see details in readme.

demo here:
https://github.com/dreambo8563/next-vue-storage-watcher/blob/main/src/App.vue

**Comment by DariaYeremina** [comment]
I was thinking the same...
